name: project-check

on: push
jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start linter
        run: |
          make lint
